# Generated by Django 4.2.15 on 2025-07-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicalcertificate_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_number', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('received', models.BooleanField()),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('dosage_strength', models.CharField(max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_number', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(choices=[('Empl', 'Employee'), ('COE', 'COE - College of Education'), ('CEA', 'CEA - College of Architecture and Engineering'), ('CBS', 'CBS - College of Business Studies'), ('CAS', 'CAS - College of Arts and Science'), ('CSSP', 'CSSP - College of Scial Science and Philosophy'), ('CCS', 'CCS - College of Computing Studies'), ('CHTM', 'CHTM - College of Hospitality and Tourism Management'), ('CIT', 'CIT - College of Industrial Technology'), ('Law', 'Law - School of Law'), ('GS', 'GS - Graduate Studies'), ('SHS', 'SHS - Senior High School'), ('LHS', 'LHS - Laboratory High School')], max_length=4)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year_and_section', models.CharField(blank=True, max_length=10)),
                ('contact_number', models.PositiveIntegerField(default='09')),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_number', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('referred_hospital', models.CharField(choices=[('The Medical City Clark', 'The Medical City Clark'), ('Angeles University Foundation Medical Center', 'Angeles University Foundation Medical Center'), ('Mother Teresa of Calcutta Medical Center', 'Mother Teresa of Calcutta Medical Center'), ('Jose B. Lingad Memorial Regional Hospital', 'Jose B. Lingad Memorial Regional Hospital'), ('San Fernandino Hospital', 'San Fernandino Hospital'), ('Mt. Carmel Medical Center', 'Mt. Carmel Medical Center'), ('Sacred Heart Medical Center', 'Sacred Heart Medical Center'), ('Our Lady of Mt. Carmel Medical Center', 'Our Lady of Mt. Carmel Medical Center')], max_length=100)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('A', 'A. Alimentary System'), ('B', 'B. Respiratory System'), ('C', 'C. Musculo-Skeletal System'), ('D', 'D. Integumentary System'), ('E', 'E. Urinary System'), ('F', 'F. Metabolic Endocrine System'), ('G', 'G. Cardiovascular System'), ('H', 'H. Eyes, Ears, Nose & Throat Disorders'), ('I', 'I. Communicable Diseases'), ('J', 'J. Blood Disorders'), ('K', 'K. Neurological Disorders'), ('L', 'L. OB-GYNE Cases'), ('M', 'M. Dental Cases'), ('N', 'N. Physical Examinations'), ('O', 'O. Referrals'), ('P', 'P. Follow-up Check-up'), ('Q', 'Q. Others')], max_length=1)),
                ('description', models.CharField(max_length=1000)),
                ('provider', models.CharField(max_length=100)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
                ('unique_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('box', 'Box'), ('piece', 'Piece')], max_length=5)),
                ('quantity_per_unit', models.PositiveIntegerField(default=1)),
                ('expiration_date', models.DateField()),
                ('initial_stocks', models.PositiveIntegerField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
                ('disposed', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('provider_updated', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.stock')),
                ('treatment_logbook', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='cms.treatment_logbook')),
            ],
        ),
    ]
