# Generated by Django 4.2.15 on 2024-08-28 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dosage_form', models.CharField(max_length=100)),
                ('dosage_strength', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('unique_number', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=2, null=True)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.PositiveIntegerField(default=0)),
                ('emergency_number', models.PositiveIntegerField(default=0)),
                ('personal_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('provider', models.CharField(max_length=100)),
                ('unique_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('referred_hospital', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('treatment_logbook', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.treatment_logbook')),
                ('unique_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prescribed', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.medicine')),
                ('treatment_logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='cms.treatment_logbook')),
            ],
        ),
        migrations.CreateModel(
            name='Medicalcertificate_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('received', models.BooleanField()),
                ('provider', models.CharField(max_length=100)),
                ('unique_number', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('inital_stocks', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.medicine')),
            ],
        ),
    ]
