# Generated by Django 5.0.7 on 2024-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('student_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('suffix', models.CharField(blank=True, max_length=256)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=256)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=256)),
                ('course', models.CharField(blank=True, max_length=256)),
                ('year', models.IntegerField(blank=True)),
                ('section', models.IntegerField(blank=True)),
            ],
        ),
    ]
