# Generated by Django 5.0.7 on 2024-08-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='section',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
