# Generated by Django 4.2.15 on 2024-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Stock',
        ),
        migrations.AlterField(
            model_name='referral',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
