# Generated by Django 5.0.6 on 2024-08-13 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_patient_data_age_alter_patient_data_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthcare_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('full_name', models.CharField(max_length=256)),
                ('contact_number', models.PositiveIntegerField(default=0)),
                ('emergency_number', models.PositiveIntegerField(default=0)),
                ('personal_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=256)),
                ('expiration_date', models.DateField()),
                ('inital_stocks', models.PositiveIntegerField(default=0)),
                ('current_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Medicalcertificate_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('student_number', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=256)),
                ('received', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('brand_name', models.CharField(max_length=256)),
                ('generic_name', models.CharField(max_length=256)),
                ('dosage_form', models.CharField(max_length=256)),
                ('dosage_strength', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_data_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('student_number', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('suffix', models.CharField(blank=True, max_length=256)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=256)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=256)),
                ('course', models.CharField(blank=True, max_length=256)),
                ('year', models.PositiveIntegerField(blank=True, default=0)),
                ('section', models.CharField(blank=True, max_length=1)),
                ('contact_number', models.PositiveIntegerField(default=0)),
                ('emergency_number', models.PositiveIntegerField(default=0)),
                ('personal_email', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=512)),
                ('referred_hospital', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('student_number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='patient_data',
        ),
    ]
