# Generated by Django 4.2.15 on 2024-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_medicalcertificate_logbook_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='initial_stocks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
