# Generated by Django 4.2.15 on 2024-09-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_stock_current_stock_alter_stock_initial_stocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_hospital',
            field=models.CharField(choices=[('The Medical City Clark', 'The Medical City Clark'), ('Angeles University Foundation Medical Center', 'Angeles University Foundation Medical Center'), ('Mother Teresa of Calcutta Medical Center', 'Mother Teresa of Calcutta Medical Center'), ('Jose B. Lingad Memorial Regional Hospital', 'Jose B. Lingad Memorial Regional Hospital'), ('San Fernandino Hospital', 'San Fernandino Hospital'), ('Mt. Carmel Medical Center', 'Mt. Carmel Medical Center'), ('Sacred Heart Medical Center', 'Sacred Heart Medical Center'), ('Our Lady of Mt. Carmel Medical Center', 'Our Lady of Mt. Carmel Medical Center')], max_length=100),
        ),
    ]
