# Generated by Django 4.2.15 on 2024-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
