# Generated by Django 4.2.15 on 2024-09-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_medicalcertificate_logbook_provider_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='provider_updated',
        ),
    ]
