# Generated by Django 4.2.15 on 2024-09-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_patient_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='provider_updated',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
