# Generated by Django 4.2.15 on 2024-09-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_patient_provider_patient_provider_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='provider_updated',
        ),
    ]
