# Generated by Django 4.2.15 on 2024-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_patient_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
