# Generated by Django 4.2.15 on 2024-09-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_patient_provider_patient_provider_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('stock_level', models.PositiveIntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'year', 'month')},
            },
        ),
    ]
