# Generated by Django 4.2.15 on 2024-09-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_monthlystock_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyStock',
        ),
    ]
