# Generated by Django 4.2.15 on 2024-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_delete_monthlystock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='section',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='year',
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('Empl', 'Employee'), ('COE', 'COE - College of Education'), ('CEA', 'CEA - College of Architecture and Engineering'), ('CBS', 'CBS - College of Business Studies'), ('CAS', 'CAS - College of Arts and Science'), ('CSSP', 'CSSP - College of Scial Science and Philosophy'), ('CCS', 'CCS - College of Computing Studies'), ('CHTM', 'CHTM - College of Hospitality and Tourism Management'), ('CIT', 'CIT - College of Industrial Technology'), ('Law', 'Law - School of Law'), ('GS', 'GS - Graduate Studies'), ('SHS', 'SHS - Senior High School'), ('LHS', 'LHS - Laboratory High School')], default='Empl', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='year_and_section',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.PositiveIntegerField(default='09'),
        ),
    ]
