# Generated by Django 4.2.15 on 2024-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_remove_patient_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment_logbook',
            name='category',
            field=models.CharField(choices=[('A', 'A. Alimentary System'), ('B', 'B. Respiratory System'), ('C', 'C. Musculo-Skeletal System'), ('D', 'D. Integumentary System'), ('E', 'E. Urinary System'), ('F', 'F. Metabolic Endocrine System'), ('G', 'G. Cardiovascular System'), ('H', 'H. Eyes, Ears, Nose & Throat Disorders'), ('I', 'I. Communicable Diseases'), ('J', 'J. Blood Disorders'), ('K', 'K. Neurological Disorders'), ('L', 'L. OB-GYNE Cases'), ('M', 'M. Dental Cases'), ('N', 'N. Physical Examinations'), ('O', 'O. Referrals'), ('P', 'P. Follow-up Check-up'), ('Q', 'Q. Others')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
