# Generated by Django 4.2.15 on 2024-09-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_treatment_logbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='year_and_section',
            field=models.CharField(blank=True, default='4A', max_length=10),
            preserve_default=False,
        ),
    ]
