# Generated by Django 4.2.15 on 2024-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_patient_height_patient_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
    ]
