# Generated by Django 4.2.15 on 2024-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_rename_received_stock_disposed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcertificate_logbook',
            name='unique_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='unique_number',
            field=models.CharField(max_length=100),
        ),
    ]
