# Generated by Django 4.2.15 on 2024-09-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_alter_medicalcertificate_logbook_unique_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='cms.stock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity_prescribed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment_logbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='cms.treatment_logbook'),
        ),
    ]
