# Generated by Django 4.2.15 on 2025-07-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_prescription_stock_alter_prescription_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
